function prompt = write_prompt_for_damped_oscillator(X_inc, models, t0, t1)

X_inc_struct.amplitude = X_inc(1);
X_inc_struct.damping_coefficient = X_inc(2);
X_inc_struct.angular_frequency = X_inc(3);
X_inc_struct.phase_offset = X_inc(4); 

m = length(models);
models_cell_array = cell(1, m);
for j = 1:m
    center_point = models(j).center_point; 
    model_struct = struct();
    model_struct.time = t0 + (j*(t1 - t0))/(m-1);
    model_struct.amplitude = center_point(1);
    model_struct.damping_coefficient = center_point(2);
    model_struct.angular_frequency = center_point(3);
    model_struct.phase_offset = center_point(4);
    %model_struct.residual = models(j).F(models(j).center_idx);
    models_cell_array{j} = model_struct;
end


prompt = "I am fitting four phenomenological parameters" ...
    + "(amplitude, damping coefficient, angular frequency, and initial phase offset) " ...
    + "of a damped harmonic oscillator to experimental data obtained by " ...
    + "measuring the displacement at " ...
    + num2str(m) + " equally spaced candidate time points from time "...
    + "t=" + num2str(t0) + " seconds to t=" + num2str(t1) + " seconds." ...
    + "I am running a forward model code that takes as input both 1) a subset of these time points and " ...
    + "2) a set of phenomenological parameters and returns simulated measurements of displacement " ...
    + "at the input time points given the input parameters (there is simulated measurement error). " ...
    + "Let's pretend that evaluating the forward model is a very expensive " ...
    + "operation (I know it isn't, but humor me). " ...
    + "In an outer loop optimization method, I am maintaining " + num2str(m) + " separate local quadratic models " ...
    + "of the displacement as a function of the four parameters, one model per each time point. " ... 
    + "Each local quadratic model is characterized by a center point, around which the model is locally valid." ...
    + "In each iteration of the optimization method, I can update a small batch of the quadratic models" ...
    + "so that their centers are all updated to a given, incumbent set of parameters. " ...
    + "At the end of this prompt, I will provide a json that shows, " ...
    + "for each value of time t, " ...
    + "where the quadratic model of the corresponding model is currently centered. " ...
    + "With this setup in mind, give me an array of length " + num2str(m) + " of "...
    + "nonnegative real-valued numbers that sum to 1.0; each entry of the " ...
    + "array should correspond to a probability with which I should "... 
    + "update the model center to the incumbent parameter estimate values "...
    + jsonencode(X_inc_struct) + " at the corresponding time point." ...
    + "I will fix your work if I have to, but please try to make sure all entries " ...
    + "of the array are nonnegative and sum to 1.0." ... 
    + "Also, please double check that there are exactly " + num2str(m) + " entries in the array." ...
    + "Think hard about the nonlinear relationship between time t and the four phenomenological parameters." ...
    + "Also think hard about the fact I am using quadratic models and what the second-order Taylor expansion " ...
    + "might tell you about the quadratic model's accuracy at the incumbent." ...
    + "Your array should take into account these considerations, as well as the distances between the incumbent and the current parameters. " ...
    + "Please respond only with a json with two fields, one containing the array," ...
    + " labelled 'array', and one containing your reasoning, labelled 'reasoning'. " ...
    + "In your reasoning, if you used any formulas to derive your array, then please tell me " ...
    + "how you interpreted the parameter names in the JSON that I provided you as symbols in your formulas. " ...
    + "Please keep in mind that I will be giving you this same prompt multiple times," ...
    + "and so you will be able to see which models I decided to update. " ...
    + "The json with the model center data I promised is: " ...
    + jsonencode(models_cell_array); 

end